Feature branch
Guy-Gustave/newsweek pull request #1
Opened 2020-06-24 17:42 UTC by Guy-Gustave

2020-06-24 18:57 UTC, elmejdki requested changes
# Great job @Guy-Gustave so far, I will not be able to review your code untill you make your repo looks professional.
### status: require changes :recycle: 

Friendly reminder: You should make sure that your repo looks professional before review.
Please take a step back and read a lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.
Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there).
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

### your pull request is messing a meaningful title and short summary, please add them and request another code review.
## Happy Coding :tophat:

2020-06-25 11:13 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @Guy-Gustave** 
Good job with your new submission for this project :muscle:  
Your page passes most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:
- [ ] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload By now the validator lint some errors in your markup.
- [ ] the search in your navbar should be an input with a search icon.
- [ ] your page has to change with the same RESPONSIVE WEN DESIGNS breakpoints of the original page.
- [ ] for the small screen size the original page shows a user icon in the header, check out:

![](https://i.imgur.com/CY8sPiMl.png)

Your page doesn't have this icon:

![](https://i.imgur.com/G7ZRnHjl.png)

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-06-25 12:46 UTC, Guy-Gustave commented
thanks for your suggestions. now I made all
![Screenshot from 2020-06-25 14-44-56](https://user-images.githubusercontent.com/56753805/85722400-8a7cd880-b6f2-11ea-9ab3-d4664d8f7fe2.png)

2020-06-25 13:40 UTC, elmejdki requested changes
# Good job so far @Guy-Gustave :clap:, but in order to make your project approved you need to make some changes. :hammer: :hammer_and_wrench: :toolbox: 
## status: require changes. :recycle: 

- [ ] fix the header please it not like the original page, they should be exactly the same:
### clone:
![image](https://user-images.githubusercontent.com/34653764/85726969-88b11600-b6ee-11ea-8679-aa203058886c.png)

### original:
![image](https://user-images.githubusercontent.com/34653764/85726049-a29e2900-b6ed-11ea-9f2d-35b79969cab2.png)

- [ ] Remove the unnecessary padding from the right and left of the top header on all screen sizes:
### desktop:
![image](https://user-images.githubusercontent.com/34653764/85726545-193b2680-b6ee-11ea-871b-8ccf6e2164c6.png)

### tablet:
![image](https://user-images.githubusercontent.com/34653764/85726422-f90b6780-b6ed-11ea-9898-a7b941d370d6.png)

- [ ] you need to hide the navbar on mobile versions:
![image](https://user-images.githubusercontent.com/34653764/85726685-3bcd3f80-b6ee-11ea-8e35-b1158cc8938a.png)

- [ ] the header should be fixed on the top, there is no header in your page:
![image](https://user-images.githubusercontent.com/34653764/85728616-fe69b180-b6ef-11ea-812b-c270a865ada0.png)

- [ ] Fix the story section:
### clone:
![image](https://user-images.githubusercontent.com/34653764/85730467-94eaa280-b6f1-11ea-820a-8fe3b8d35611.png)
### original:
![image](https://user-images.githubusercontent.com/34653764/85730575-aaf86300-b6f1-11ea-834b-33d8f2003d51.png)

- [ ] Fix in the magazine section, fix the title and the articles one by one:
### clone:
![image](https://user-images.githubusercontent.com/34653764/85730052-3d4c3700-b6f1-11ea-9c66-e3cd998aaf7e.png)

### original:
![image](https://user-images.githubusercontent.com/34653764/85729989-30c7de80-b6f1-11ea-8e6a-2a7d50c15c89.png)

- [ ] Fix the Editor Pick's section, fix the title and the articles:
### clone:
![image](https://user-images.githubusercontent.com/34653764/85729765-fbbb8c00-b6f0-11ea-9318-e98609a9729f.png)

### original:
![image](https://user-images.githubusercontent.com/34653764/85729677-ec3c4300-b6f0-11ea-9ad7-0712cb00dc73.png)

 
- [ ] Fix the feature slideshow:
### clone:
![image](https://user-images.githubusercontent.com/34653764/85729422-b72ff080-b6f0-11ea-97c7-1aaa2329285f.png)

### original:
![image](https://user-images.githubusercontent.com/34653764/85729486-c4e57600-b6f0-11ea-984a-0a10c4d8c4f4.png)


- [ ] The subscribe section looks terrible please fix it:
### clone:
![image](https://user-images.githubusercontent.com/34653764/85729146-759f4580-b6f0-11ea-98fd-56281b2a0bd1.png)
### original:
![image](https://user-images.githubusercontent.com/34653764/85729201-818b0780-b6f0-11ea-9f78-d60763f58b28.png)


- [ ] Fix the footer please, it not like the original at all:
### clone: 
![image](https://user-images.githubusercontent.com/34653764/85728977-4ee10f00-b6f0-11ea-8eaa-fb22e38452fb.png)

### original:
![image](https://user-images.githubusercontent.com/34653764/85728931-4557a700-b6f0-11ea-84b1-47799cd2fc6c.png)

2020-06-25 13:40 UTC, elmejdki commented on README.md
> +<<<<<<< HEAD
Remove this line if you don't have a reason to keep it

2020-06-25 13:40 UTC, elmejdki commented on README.md
> +>>>>>>> 69df58657c1bef21d3ded63c00b36b42b667e919
Remove this line if you don't have a reason to keep it

2020-06-25 13:40 UTC, elmejdki commented on index.html
> +      <nav class="d-flex flex-column navbar px-0 mx-0 w-100">
remove the flex column it's ruining the top header.

2020-06-25 13:40 UTC, elmejdki commented on index.html
> +        <div class="logo col-4 col-lg-4">
why are you using col????, please remove it it's unnecessary.

2020-06-25 13:40 UTC, elmejdki commented on index.html
> +        <li>the debate</li>
center the text inside the li's, cause they are not centered, you can use text-center:
![image](https://user-images.githubusercontent.com/34653764/85727920-57851580-b6ef-11ea-8880-4e06f844be76.png)

2020-06-25 16:01 UTC, Guy-Gustave commented
i removed the second navbar and all title also the section before the footer. thankx i hope now all is okay

2020-06-25 17:47 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @Guy-Gustave ! 👋 
You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- **General**

- [ ] A horizontal scroll appears on your project in both the large and small screen sizes. Please fix this. 
Small screen 👇 
![Screen Shot 2020-06-25 at 7 03 24 PM](https://user-images.githubusercontent.com/48804258/85765602-8e225680-b716-11ea-9332-991796fb273c.png)
Large Screen 👇 
![Screen Shot 2020-06-25 at 7 01 52 PM](https://user-images.githubusercontent.com/48804258/85765371-56b3aa00-b716-11ea-9145-477f7965887f.png)


- **Navigation Bar**

- [ ] There is still no input with a search icon. This was requested by a previous TSE. Please fix this.
Your clone 👇 
![Screen Shot 2020-06-25 at 7 05 40 PM](https://user-images.githubusercontent.com/48804258/85765927-dd688700-b716-11ea-8fd4-545d8d7f1223.png)
The original page 👇 
![Screen Shot 2020-06-25 at 7 06 09 PM](https://user-images.githubusercontent.com/48804258/85766009-ef4a2a00-b716-11ea-82a1-451c8371fde5.png)

- [ ] As was requested by the previous TSE, your navigation bar should look more similar to the original page. The background of the login should not be white. Please fix this. 
Your clone 👇 
![Screen Shot 2020-06-25 at 7 09 23 PM](https://user-images.githubusercontent.com/48804258/85766497-6253a080-b717-11ea-8d4a-7ae54fb44742.png)
The original page 👇 
![Screen Shot 2020-06-25 at 7 09 39 PM](https://user-images.githubusercontent.com/48804258/85766533-6bdd0880-b717-11ea-9ea8-5784381230f7.png)

- [ ] The links just below the read header should be centered. Yours are aligned to the right. Please fix this.
Your clone 👇 
![Screen Shot 2020-06-25 at 7 11 30 PM](https://user-images.githubusercontent.com/48804258/85766809-ae064a00-b717-11ea-9b93-f53082255045.png)
The original page 👇 
![Screen Shot 2020-06-25 at 7 11 46 PM](https://user-images.githubusercontent.com/48804258/85766851-b8284880-b717-11ea-8079-a8af9cc65aa2.png)

- [ ] Your navigation bar is not responsive on the smaller screen size. Please compare your clone with the original page in the screenshots below and fix this. 
Your clone 👇 
![Screen Shot 2020-06-25 at 7 13 26 PM](https://user-images.githubusercontent.com/48804258/85767096-f3c31280-b717-11ea-926b-ab8cf99f5611.png)
The original page 👇 
![Screen Shot 2020-06-25 at 7 14 39 PM](https://user-images.githubusercontent.com/48804258/85767254-1f45fd00-b718-11ea-84ef-0bd8ab98e234.png)

- [ ] The previous reviewer requested that your header remain fixed at the top of the page, but you have not yet done this. Please implement this requested feature. 


- **Stories sections**
 

- [ ] The top story is missing the article image tag. Please compare your clone with the original page and fix this. 
Your clone 👇 
![Screen Shot 2020-06-25 at 7 18 49 PM](https://user-images.githubusercontent.com/48804258/85767831-b448f600-b718-11ea-85f1-998530a0ccb2.png)
The original page 👇 
![Screen Shot 2020-06-25 at 7 19 13 PM](https://user-images.githubusercontent.com/48804258/85767881-c1fe7b80-b718-11ea-841e-6ee8a1eec71a.png)

- [ ] The image tags on all of the other images are not properly positioned. Please see a few screenshots of the issue below. 
Your clone 👇 
![Screen Shot 2020-06-25 at 7 20 39 PM](https://user-images.githubusercontent.com/48804258/85768102-f5d9a100-b718-11ea-9074-97dbf8be6ffe.png)
The original page 👇 
![Screen Shot 2020-06-25 at 7 21 00 PM](https://user-images.githubusercontent.com/48804258/85768144-025df980-b719-11ea-9e2e-b662b5df63da.png)
Your clone 👇 
![Screen Shot 2020-06-25 at 7 21 32 PM](https://user-images.githubusercontent.com/48804258/85768209-1570c980-b719-11ea-92e1-493bc11ff89d.png)

The original page 👇 
![Screen Shot 2020-06-25 at 7 21 49 PM](https://user-images.githubusercontent.com/48804258/85768256-1f92c800-b719-11ea-85fe-fa6cfa082425.png)

- [ ] These elements should take up more of the width of the page. Please fix this. 
![Screen Shot 2020-06-25 at 7 25 36 PM](https://user-images.githubusercontent.com/48804258/85768757-a6e03b80-b719-11ea-9d4d-87f3394700ef.png)


- **In the magazine section**

- [ ] The previous reviewer requested that you improve the titles and articles. Please compare your clone to the original and fix this.
The original page 👇 
![Screen Shot 2020-06-25 at 7 27 57 PM](https://user-images.githubusercontent.com/48804258/85769094-fa528980-b719-11ea-92d6-9ee3c2afd40e.png)
Your clone 👇 
![Screen Shot 2020-06-25 at 7 28 15 PM](https://user-images.githubusercontent.com/48804258/85769152-05a5b500-b71a-11ea-8f9a-30bb18d8b585.png)

- [ ] On the medium screen size, the article tags are overlapping. Please fix this.
Your clone 👇 
![Screen Shot 2020-06-25 at 7 29 31 PM](https://user-images.githubusercontent.com/48804258/85769355-32f26300-b71a-11ea-8779-497fd0bfcc66.png)
The original page 👇 
![Screen Shot 2020-06-25 at 7 29 49 PM](https://user-images.githubusercontent.com/48804258/85769400-3d146180-b71a-11ea-994a-6ba69329a982.png)

- [ ] The articles should take up more of the width of the page in the small screen size. 
The original page 👇 
![Screen Shot 2020-06-25 at 7 30 58 PM](https://user-images.githubusercontent.com/48804258/85769569-6634f200-b71a-11ea-956e-a25814b73980.png)
Your clone 👇 
![Screen Shot 2020-06-25 at 7 31 21 PM](https://user-images.githubusercontent.com/48804258/85769627-74830e00-b71a-11ea-9dae-82ca95bd7e8e.png)

- **Editor's Picks section**

- [ ] The article tags are not properly aligned. Please fix this. 
Your clone 👇 
![Screen Shot 2020-06-25 at 7 32 15 PM](https://user-images.githubusercontent.com/48804258/85769748-94b2cd00-b71a-11ea-95f8-e185324da213.png)
The original page 👇 
![Screen Shot 2020-06-25 at 7 32 38 PM](https://user-images.githubusercontent.com/48804258/85769805-a2685280-b71a-11ea-9c61-ecc25d7f359c.png)

- [ ] On the medium screen and small screen size, the articles should have less padding on either side. 
The original page 👇 
 _(medium)_
![Screen Shot 2020-06-25 at 7 33 39 PM](https://user-images.githubusercontent.com/48804258/85769975-c6c42f00-b71a-11ea-8d9f-659eec9670d3.png)
_(small)_
![Screen Shot 2020-06-25 at 7 35 10 PM](https://user-images.githubusercontent.com/48804258/85770243-fd9a4500-b71a-11ea-8866-97ee8c659a4d.png)

Your clone 👇 
 _(medium)_
![Screen Shot 2020-06-25 at 7 33 55 PM](https://user-images.githubusercontent.com/48804258/85770038-d0e62d80-b71a-11ea-96a6-f50894b36907.png)
_(small)_
![Screen Shot 2020-06-25 at 7 35 34 PM](https://user-images.githubusercontent.com/48804258/85770293-0ab73400-b71b-11ea-95b9-e26159436f6c.png)



- **Featured slideshow section**

- [ ] The article images listed on the side are not big enough. Please fix this as was requested by the previous TSE. 
Your clone 👇 
![Screen Shot 2020-06-25 at 7 37 24 PM](https://user-images.githubusercontent.com/48804258/85770524-4ce07580-b71b-11ea-847f-3b587efff9b3.png)
The original page 👇 
![Screen Shot 2020-06-25 at 7 37 46 PM](https://user-images.githubusercontent.com/48804258/85770574-5964ce00-b71b-11ea-9d43-d7853ae45114.png)

- [ ] On the medium screen, the images shrink to a size that is way too small. Please fix this. 
Your clone 👇 
![Screen Shot 2020-06-25 at 7 38 37 PM](https://user-images.githubusercontent.com/48804258/85770677-78636000-b71b-11ea-8efb-47883781dc63.png)
The original page 👇 
![Screen Shot 2020-06-25 at 7 38 58 PM](https://user-images.githubusercontent.com/48804258/85770729-84e7b880-b71b-11ea-94c3-e5145debe334.png)


- **Subscribe & Newsletter section**

- [ ] The previous reviewer requested that you fix this section. You have not appeared to have done this. Please compare your clone with the original and fix this. It does not at all look similar to the original. 
The original page 👇 
_(Large)_
![Screen Shot 2020-06-25 at 7 41 25 PM](https://user-images.githubusercontent.com/48804258/8577106 [...]

2020-06-26 18:51 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning:
Hey @Guy-Gustave :wave:
-
You have done a splendid job! :tada: Keep it up.
We, however, still do have some few changes to carry out before we proceed (see review comment).
##
Kindly take note of the differences below 👇 and work on the suggested changes.

## Main Section Changes

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://raw.githack.com/Guy-Gustave/newsweek/feature-branch/index.html)|
|:---:|:---:|
|![source](https://user-images.githubusercontent.com/22345961/85890132-7372df00-b7f5-11ea-86af-3daaf5ad8f41.png)|![clone](https://user-images.githubusercontent.com/22345961/85890149-7bcb1a00-b7f5-11ea-925c-6be09c9ba243.png)|

- Improve on the styling of the Newsweek logo, the login and the subscribe buttons as well. Make sure the Newsweek logo gets centred in the navbar as well. 
- Remove the black borders on all the section articles on the page. 
- Centre the entire contents of the page just as in the source page.

## In the magazine section
|[Source Page](https://www.newsweek.com/)|[Clone Page](https://raw.githack.com/Guy-Gustave/newsweek/feature-branch/index.html)|
|:---:|:---:|
|![in-the-magazine](https://user-images.githubusercontent.com/22345961/85890378-e9774600-b7f5-11ea-9ce2-95c94c0cee93.png)|![in-the-magazine-clone](https://user-images.githubusercontent.com/22345961/85890399-f09e5400-b7f5-11ea-98e4-976da38c86ac.png)|

- Let's work on the differences highlighted above in this section. From the fonts to the spacing of both the headers articles and the articles themselves.

## Editors pick
|[Source Page](https://www.newsweek.com/)|[Clone Page](https://raw.githack.com/Guy-Gustave/newsweek/feature-branch/index.html)|
|:---:|:---:|
|![editors-pick](https://user-images.githubusercontent.com/22345961/85890544-3ce99400-b7f6-11ea-9219-cb85ed8c185d.png)|![editors-pick-clone](https://user-images.githubusercontent.com/22345961/85890555-42df7500-b7f6-11ea-8fbc-4636a914f9c5.png)|
- Improve on the styling of the editors pick, kindly.
## US, World, etc section
|[Source Page](https://www.newsweek.com/)|[Clone Page](https://raw.githack.com/Guy-Gustave/newsweek/feature-branch/index.html)|
|:---:|:---:|
|![us](https://user-images.githubusercontent.com/22345961/85890615-61de0700-b7f6-11ea-9d48-8ef4e5cddd2d.png)|![us-clone](https://user-images.githubusercontent.com/22345961/85890621-67d3e800-b7f6-11ea-826d-94743fc19eed.png)|
- Remove the black border on all the articles and make sure the height of the rightmost articles are increased to match the source page. 
## Footer Section 
|[Source Page](https://www.newsweek.com/)|[Clone Page](https://raw.githack.com/Guy-Gustave/newsweek/feature-branch/index.html)|
|:---:|:---:|
|![footer](https://user-images.githubusercontent.com/22345961/85890805-c1d4ad80-b7f6-11ea-960f-b80efec64d03.png)|![footer-clone](https://user-images.githubusercontent.com/22345961/85890824-c731f800-b7f6-11ea-9cd6-ca78c0375748.png)|
- Improve on the styling on the footer.
## 

### Kindly work on the responsiveness as well. So far there is som much responsiveness with the page.
##
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-26 22:42 UTC, BrittanyBlake requested changes
### Status: Changes Required  🏗️ 🔨 
****
### Hello @Guy-Gustave   👋 
You are doing a great job with this project! 👍 You are almost done! 💪 Great job applying the feedback you have received from myself and the other TSEs. 🎖️ 🌟 There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] There are no linter checks available in your repo. Please ensure that stickler is enabled. 

- [ ] Your login button is still not the same as the original. Please note that it should be the same background color as the header with white text. 
Your clone 👇 
![Screen Shot 2020-06-27 at 12 17 29 AM](https://user-images.githubusercontent.com/48804258/85905400-97d9b600-b80b-11ea-998c-c74e3feb17b3.png)
The original page 👇 
![Screen Shot 2020-06-27 at 12 17 50 AM](https://user-images.githubusercontent.com/48804258/85905422-a45e0e80-b80b-11ea-9456-2684cc7244d6.png)

- [ ] Your header needs to be improved on the **small screen**. In your clone, the logo overlaps with the other elements of the navigation. Additionally, there is too much empty space on the right, the header should take the full width of the page. 
Your clone 👇 
![Screen Shot 2020-06-27 at 12 19 44 AM](https://user-images.githubusercontent.com/48804258/85905524-e8511380-b80b-11ea-90ec-55436598f1f3.png)
 The original page 👇 
![Screen Shot 2020-06-27 at 12 20 40 AM](https://user-images.githubusercontent.com/48804258/85905572-09196900-b80c-11ea-89aa-dee59ba46904.png)

- [ ] The side articles in the featured slideshow section on the **medium screen** are still way too small. Please fix this. 
Your clone 👇 
![Screen Shot 2020-06-27 at 12 25 39 AM](https://user-images.githubusercontent.com/48804258/85905806-bbe9c700-b80c-11ea-9087-c1909c953468.png)
The original page 👇 
![Screen Shot 2020-06-27 at 12 26 30 AM](https://user-images.githubusercontent.com/48804258/85905841-da4fc280-b80c-11ea-824e-ceaecdd65d86.png)

- [ ] Please improve the in the magazine section as was requested by the previous TSE. 
Your clone 👇 
![Screen Shot 2020-06-27 at 12 28 09 AM](https://user-images.githubusercontent.com/48804258/85905913-15ea8c80-b80d-11ea-9fd0-1c652109fa73.png)
The original page 👇 
![Screen Shot 2020-06-27 at 12 28 37 AM](https://user-images.githubusercontent.com/48804258/85905933-2569d580-b80d-11ea-83e7-54e6e9e1a9d0.png)

- Your footer is not at all like the original nor is it responsive. 
**Large screen**

- [ ] The subscribe section should have **two** magazine covers **overlapping**. Additionally, your subscribe button is not formatted correctly and the text should be **left-aligned** not centered. Please fix. 
Your clone 👇 
![Screen Shot 2020-06-27 at 12 31 38 AM](https://user-images.githubusercontent.com/48804258/85906095-91e4d480-b80d-11ea-9559-00b9138fadeb.png)
The original page 👇 
![Screen Shot 2020-06-27 at 12 30 20 AM](https://user-images.githubusercontent.com/48804258/85906024-63ff9000-b80d-11ea-948c-3db2c1712431.png)

- [ ] The image in the newsletter section is covering the text. Additionally, the text should be left-aligned not centered and the image should take the full height of the page. 
Your clone 👇 
![Screen Shot 2020-06-27 at 12 33 56 AM](https://user-images.githubusercontent.com/48804258/85906205-e425f580-b80d-11ea-8846-ea94e23cab82.png)
The original page 👇 
![Screen Shot 2020-06-27 at 12 34 16 AM](https://user-images.githubusercontent.com/48804258/85906220-f011b780-b80d-11ea-83ae-deffcf8489f3.png)
**Medium Screen**

- [ ] The newsletter and subscribe sections should both align to **one** element per row.
Your clone 👇 
![Screen Shot 2020-06-27 at 12 36 20 AM](https://user-images.githubusercontent.com/48804258/85906318-3a933400-b80e-11ea-9982-264bad849d8e.png)
The original page 👇 
![Screen Shot 2020-06-27 at 12 36 53 AM](https://user-images.githubusercontent.com/48804258/85906341-4da60400-b80e-11ea-8ac2-322c62ec0719.png)

- [ ] In addition to the fact that the newsletter section should have **two overlapping magazine covers**, the text **should not be centered** and the image **should not shrink to a smaller size.**
The original page 👇 
![Screen Shot 2020-06-27 at 12 38 06 AM](https://user-images.githubusercontent.com/48804258/85906387-79c18500-b80e-11ea-8db3-0612cfbc7eb7.png)
Your clone 👇 
![Screen Shot 2020-06-27 at 12 38 29 AM](https://user-images.githubusercontent.com/48804258/85906419-86de7400-b80e-11ea-9378-6928e417d36e.png)

- [ ] In the subscribe section, the image in your clone completely covers the text. This should not happen. 
The original page 👇 
![Screen Shot 2020-06-27 at 12 39 52 AM](https://user-images.githubusercontent.com/48804258/85906476-b8efd600-b80e-11ea-9d80-101288c7adc8.png)
Your clone 👇 
![Screen Shot 2020-06-27 at 12 40 14 AM](https://user-images.githubusercontent.com/48804258/85906485-c5742e80-b80e-11ea-9e14-48bcee941adf.png)

- [ ] Both the newsletter and the subscribe sections need to be improved on the small screen. Please compare your clone with the original and fix this.
Your clone 👇 
![Screen Shot 2020-06-27 at 12 41 29 AM](https://user-images.githubusercontent.com/48804258/85906554-f2284600-b80e-11ea-9c64-844b87006361.png)
The original page 👇 
![Screen Shot 2020-06-27 at 12 42 05 AM](https://user-images.githubusercontent.com/48804258/85906579-079d7000-b80f-11ea-9ebb-1cb3798ee96f.png)
![Screen Shot 2020-06-27 at 12 42 14 AM](https://user-images.githubusercontent.com/48804258/85906585-0d935100-b80f-11ea-9794-8803644ad4b6.png)








****
### Kindly make the required changes and resubmit for a new code review once you are ready 🙏


Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-06-27 08:56 UTC, Guy-Gustave commented
after correction of the navbar, articles of the right sidebar and the section before the footer

2020-06-27 10:17 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🛑

## Hello @Guy-Gustave 👋, you have done an incredible job making the changes. 

However, we still need to work on some more issues before we can merge.

### Remember to make *ALL* the changes requested by previous TSEs *BEFORE* requesting for another code review. In addition to that,

- There is a horizontal scrollbar in your clone. Find out what's causing it and fix that.
![Annotation 2020-06-27 153729](https://user-images.githubusercontent.com/57726348/85919784-24c45400-b88c-11ea-97c5-6261f6d620f3.jpg)

- The clone must have some space on either side like the original.

#### Clone
![image](https://user-images.githubusercontent.com/57726348/85919805-4cb3b780-b88c-11ea-9371-f2ca6f0fce85.png)

#### Original
![image](https://user-images.githubusercontent.com/57726348/85919820-5f2df100-b88c-11ea-9984-2838eab9145c.png)

- Your clone is breaking in the mobile view.

![image](https://user-images.githubusercontent.com/57726348/85919945-378b5880-b88d-11ea-9ced-a1dee4a51a99.png)

### Please make sure that you have applied the changes suggested by previous TSEs. 

Happy coding 👨‍💻

2020-06-27 11:22 UTC, Guy-Gustave commented
I finish making the correction you told me again. i hope now all required i made thank you

2020-06-27 11:53 UTC, sumancrest0001 requested changes
**Hello @Guy-Gustave,** I appreciate your work and effort. It looks nice but we need to fix some major issues before moving ahead. As you know this is a clone project and we have to make it very similar to the original site in terms of design layout as well as responsiveness. Therefore, let's put a little bit more effort into it and make it a perfect clone of the original Newsweek's site. We have to focus on alignments of elements, margin, and padding. Currently, It is also not as responsive as we want. Please compare your layout with the original one and make necessary changes especially on the subscribe and newsletter section. Furthermore, It seems like you forgot to enable the stickler. Please enable it and remove errors if any.

**Kindly make the required changes suggested by the TSEs and request for another review.
If you need help, message me on slack Suman Shrestha
happy weekends and coding :slightly_smiling_face:**

2020-06-27 16:26 UTC, Guy-Gustave commented
I need another review I hope now all required done, i activated linters again and other suggestions

2020-06-27 17:08 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🛑

## Hello @Guy-Gustave 👋, it's me again. I see you are making an effort and I really appreciate it 👏👏. Just a very few changes needed.

- Your README files contain lines from previous merge conflicts. Please remove them. It looks unprofessional. The previous TSE has also pointed this out.

![image](https://user-images.githubusercontent.com/57726348/85927339-15143200-b8c3-11ea-92c6-5a20ae20cb53.png)

![image](https://user-images.githubusercontent.com/57726348/85927346-1d6c6d00-b8c3-11ea-834b-b3c862ee4ab2.png)

- I see that you have made an effort to remove the horizontal scrollbar. But your solution has introduced another bug which is present all over the clone.

Here I have pointed a few.
![Annotation 2020-06-27 221420](https://user-images.githubusercontent.com/57726348/85927430-9a97e200-b8c3-11ea-9585-a7a5247c4de3.jpg)

You have applied `overflow-x: hidden;` to the global selector, which is not a solution, but a band-aid. This is also the reason for random scrollbars appearing on elements. Try to find exactly what element is causing the overflow and then fix that. [Here](https://chrome.google.com/webstore/detail/pesticide-for-chrome/bblbgcheenepgnnajgfpiicnbbdmmooh) is a great tool for debugging these kinds of issues.

- Good thinking on using Bootstrap cards for article containers 👌. But cards come with borders on all sides. The original does not have borders on all sides. They have borders on the bottom (or top, depending on your preference). Remember to remove excess borders to match the original.

#### Clone
![Annotation 2020-06-27 222201](https://user-images.githubusercontent.com/57726348/85927656-35dd8700-b8c5-11ea-878a-112fabf904b8.jpg)

#### Original
![image](https://user-images.githubusercontent.com/57726348/85927663-3d049500-b8c5-11ea-9d96-c70697ae67db.png)

- In `newsletter` section, the heading must be on the left side. Right now it's on the right side.

#### Clone
![Annotation 2020-06-27 223023](https://user-images.githubusercontent.com/57726348/85927763-cfa53400-b8c5-11ea-9c4c-d539b292c74a.jpg)

#### Original
![Annotation 2020-06-27 223111](https://user-images.githubusercontent.com/57726348/85927782-eba8d580-b8c5-11ea-8d96-3133e2a7079f.jpg)

- Also, the image is missing in desktop mode.

#### Clone
![image](https://user-images.githubusercontent.com/57726348/85927804-0ed38500-b8c6-11ea-8a91-6b77cdc13dab.png)

#### Original
![image](https://user-images.githubusercontent.com/57726348/85927811-17c45680-b8c6-11ea-8446-f6375e2a84e1.png)

- `subscribe` section does not match the original in tablet mode,

#### Clone
![image](https://user-images.githubusercontent.com/57726348/85927870-80abce80-b8c6-11ea-86a8-956f4703eefb.png)

#### Original
![image](https://user-images.githubusercontent.com/57726348/85927892-94573500-b8c6-11ea-9c0e-728931d06392.png)

- In the mobile view, your `subscribe/newsletter` section is not responsive.

#### Clone
![image](https://user-images.githubusercontent.com/57726348/85927903-aa64f580-b8c6-11ea-9477-045c22701882.png)

#### Original
![image](https://user-images.githubusercontent.com/57726348/85927921-cec0d200-b8c6-11ea-9e32-0270863a283f.png)

Everything is coming together now. Just a few more to go.

Happy coding 👨‍💻

2020-06-27 20:35 UTC, Guy-Gustave commented
after removing all border cards and changer the over-flow by fixing the elements that were flowing, also readme. by many different corrections, I still have hope but I hope now okay. thank you

2020-06-27 21:35 UTC, HADDADSOHAIB requested changes
### Status: Change Required :recycle: 

### Hi everyone   :hand: 

### Great project, godd work, you implemented a lot of required changes, but there is some changes to be made:

- These navigation elements should be **links**, which are not in your clone
![Screenshot from 2020-06-27 22-18-31](https://user-images.githubusercontent.com/26064042/85932457-43464180-b8c4-11ea-93c0-d3560b63b78d.png)
- Please decrease the size of the logo in medium and small width.
clone:
![Screenshot from 2020-06-27 22-20-54](https://user-images.githubusercontent.com/26064042/85932501-902a1800-b8c4-11ea-93a4-5f19139eff2c.png)
original:
![Screenshot from 2020-06-27 22-21-43](https://user-images.githubusercontent.com/26064042/85932516-9f10ca80-b8c4-11ea-90a0-7751e91f6a36.png)
- Please remove the horizontal scroll bar:
![Screenshot from 2020-06-27 22-24-47](https://user-images.githubusercontent.com/26064042/85932588-3118d300-b8c5-11ea-971e-3d4c4d668ed5.png)
- I think this part needs some improvement, the alignment and the size of the image are not ok in the medium widths.
clone:
![Screenshot from 2020-06-27 22-28-51](https://user-images.githubusercontent.com/26064042/85932647-cae08000-b8c5-11ea-95a5-854e283c9f32.png)
Original:
![Screenshot from 2020-06-27 22-29-26](https://user-images.githubusercontent.com/26064042/85932660-d633ab80-b8c5-11ea-8dda-0af4a2071976.png)
- The newsletter in small widths is broken:
clone:
![Screenshot from 2020-06-27 22-33-13](https://user-images.githubusercontent.com/26064042/85932705-45a99b00-b8c6-11ea-9e7a-19675340eeff.png)
- original:
![Screenshot from 2020-06-27 22-33-02](https://user-images.githubusercontent.com/26064042/85932710-50643000-b8c6-11ea-9182-cf83d006d738.png)
### Once done with the changes, please ask for another code review.

2020-06-27 23:53 UTC, Guy-Gustave commented
can you see it again. I hope now okay

2020-06-28 01:30 UTC, christianotieno requested changes
### Hello, Gustave. I picked up a couple of things while going through this PR. I noticed how much of a task, the project must have been for you. It must have been overwhelming, but for some reason, you kept on going, and never gave up. Keep up with the spirit. I will, however, share some notes below. Kindly read on them before moving on. 
##
## The page has almost all the sections that are required. Good job with that.
- The styling was a major issue with this project. Most of my colleagues, I included tried raising these issues in this PR. Some of the issues were resolved some not. I would suggest taking some time to go through the changes and figure out how you faired.

## The commit messages 
- Though not clear enough, could always be improved. You ought to have ensured the commits were deceptive.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_commits.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)). Have a look at this [article](https://chris.beams.io/posts/git-commit/) for more about improving on your commit messages.
## Guidelines for sending in a Code Review Request.
- The project, when sent in for a review, was still incomplete. from the dashboard, the rule is to always send in a complete project for review.  That was never the case. let's adhere to this guiding principle next time, please.
## Advice
- Take some time and compare the source page with the clone then work on all the changes step by step. You don't need to rush. After which be sure to validate the markup as well. When you are done and truly believe everything looks strikingly similar to the source page in this assignment then you can send it in for a review. Avoid sending in unfished work kindly. Thank you!

2020-06-29 10:35 UTC, trekab requested changes
## Changes Required! :recycle: 

Hi @Guy-Gustave, I have noticed that you haven't implemented all the mandatory feedback from
[this review](https://github.com/Guy-Gustave/newsweek/pull/1#pullrequestreview-438726097). It will be a lot easier and faster if you worked on all the changes before you requested for another code review.

__P.S__: If you feel that you need extra assistance(1 on 1), reach out to a full-time T.S.E. Check out [this article](https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-) about how you can schedule time with a full-time T.S.E

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-06-29 14:15 UTC, Guy-Gustave commented
i have tried to make all required and suggested. thank you.html validator, linters, add search icon in navbar.

2020-06-29 18:10 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-06-29 18:21 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @Guy-Gustave, great job with this project :+1: I appreciate your determination to learn and improve :smile: However, most of the comments by the previous TSE's were not addressed. I would highlight some of them you can get them addressed. Kindly be patient and ensure the comments are addressed before you send another code review :100: Below are the comments
- Our page is not responsive on medium devices, let us address it by comparison. We could compare our project with the original project, [newsweek](https://www.newsweek.com/) so we can fix the responsiveness
- It was mentioned earlier that the navigation links should be clickable links, it has not been addressed, kindly fix it
- Kindly compare the screenshot below and fix the size of the images
``` clone ```
![im](https://user-images.githubusercontent.com/46388113/86041304-ff267e80-ba34-11ea-98c7-d101737c95f0.png)
``` source ```
![im1](https://user-images.githubusercontent.com/46388113/86041341-0b124080-ba35-11ea-8981-9f3c550bb18b.png)

Kindly address these comments and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-06-29 19:10 UTC, Guy-Gustave commented
hello addo, thank you for your suggestion, i cannot give up. i tried to change the navigation links and the size image. and correct some responsivness

2020-06-29 19:31 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi @Guy-Gustave, congratulations :star: You hard work and dedications has really paid off :100: 

Go ahead and merge to master, do not forget to submit the project completion form :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-06-29 19:59 UTC, merged